
name: Test Python Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Import
      run: |
        python -c "import pandas as pd; import requests; import streamlit as st; import plotly.graph_objects as go; import lime; import numpy as np; import matplotlib.pyplot as plt"
      
    - name: Run Unit Tests
      run: |
        pytest
