name: Deploy Streamlit App to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
<<<<<<< HEAD
        git remote add heroku https://git.heroku.com/applicat.git
        git push heroku master
=======
        git remote add heroku https://git.heroku.com/<applicat>.git
        HEAD
        git push heroku master

        git push heroku master
        b084b78515f2609081309f2e0a4f791882fb5cc4
        
>>>>>>> 6c8bbe347c811d6f1bd2b72f9fc8f4a889fae11b
